//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMHProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string TMH_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Manager { get; set; }
        public string Overall_LOE { get; set; }
        public string Role1 { get; set; }
        public string Role1_LOE { get; set; }
        public string Role2 { get; set; }
        public string Role2_LOE { get; set; }
        public string Role3 { get; set; }
        public string Role3_LOE { get; set; }
        public string Role4 { get; set; }
        public string Role4_LOE { get; set; }
        public string Role5 { get; set; }
        public string Role5_LOE { get; set; }
        public string Notes { get; set; }
        public bool Closed { get; set; }
    }
}
